server:
    port: 9001
eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://127.0.0.1:9000/eureka/
spring:
    application:
        name: eureka-client